name             'mssqlserver_alwayson'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mssqlserver_alwayson'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.1'
depends			 'windows'
depends      'powershell'
depends      'mssqlserver'
depends      'windows_firewall'